package ru.itis.model;

public enum Specialization {
    DRESSING_ROOM, THERAPY, GYNECOLOGY, UROLOGY, PROCTOLOGY, X_RAY_ROOM, CARDIOLOGY, ANALYZES, PEDIATRICS,
    DENTISTRY, OBSTETRICS, ULTRASOUND, GASTROENTEROLOGY, SURGERY, DERMATOLOGY, NEUROLOGY, OTORHINOLARYNGOLOGY,
    OPHTHALMOLOGY, OSTEOPATHY, PSYCHOLOGY, ENDOCRINOLOGY, MASSAGE, ALLERGOLOGY;
}
